site_name: ASF SAR Data Search Manual
site_description: Documentation for searching and processing ASF SAR data.
site_dir: 'docs'
docs_dir: 'markdown-docs'
google_analytics: ['G-440184110', 'docs.asf.alaska.edu']
extra_css:
  - 'css/styles.css'
  - 'assets/stylesheets/asf.css'
extra:
  analytics:
    - provider: google
    - property: G-440184110

theme:
    name: material
    custom_dir: asf_theme
    logo: assets/images/ASFLogo-Blue2.png
    favicon: assets/images/favicon.ico
    analytics:
      gtag: G-440184110

copyright: Copyright @ Alaska Satellite Facility

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "ASF SAR Data Search Manual"
        - locale: es
          name: Español
          build: true
          site_name: "ASF SAR Manual de Búsqueda de Datos"
          nav_translations:
            Home: Inicio
            Vertex Manual: Manual Vertex
            Baseline: Baseline
            SBAS: SBAS
            Event: Evento
            Derived Datasets: Conjuntos de Datos
            What's New: Novedades
            Tutorial Videos: Videos Tutoriales
            Source Code: Código Fuente
            Custom Processing: Procesamiento Personalizado
            Python Search Package: Paquete de Búsqueda en Python
            Basics: Básicos
            Searching: Búsqueda
            Downloading: Descarga
            Classes: Clases
            Exceptions: Excepciones
            ASF Search API: API de Búsqueda ASF
            Search API Basics:  Básicos de la API de búsqueda
            Search API Keywords & Endpoints: Palabras Clave y Puntos Finales de la API de Búsqueda
            Tools: Herramientas
            Troubleshooting: Solución de Problemas
            Cookbook: Recetario
            Product Details: Detalles del Producto
            Using ASF Data: Utilizando Datos de ASF
            ALOS PALSAR Products: Productos ALOS PALSAR
            Events (SARVIEWS): Eventos (SARVIEWS)

  - mkdocs-video:
     css_style:
        position: "relative"
        width: "50%"
        max-width: "400px"
        min-width: "300px"
        height: "25vw"
        max-height: "250px"
        min-height: "175px"

nav:
  - Home: index.md
  - Vertex:
    - Vertex Manual:
      - vertex/manual.md
    - Baseline: vertex/baseline.md
    - SBAS: vertex/sbas.md
    - Event: vertex/events.md
    - Derived Datasets: vertex/derived_datasets.md
    - What's New: vertex/changelog.md
    - Tutorial Videos: https://www.youtube.com/playlist?list=PLXluIEvp5ZzIWd0yNy-ANfdwWjCD1hInA
    - Source Code: https://github.com/asfadmin/Discovery-SearchUI
  - Custom Processing: https://hyp3-docs.asf.alaska.edu
  - Python Search Package:
    - Basics: asf_search/basics.md
    - Searching: asf_search/searching.md
    - Downloading: asf_search/downloading.md
    - Classes:
      - ASFProduct: asf_search/ASFProduct.md
      - ASFSearchOptions: asf_search/ASFSearchOptions.md
      - ASFSearchResults: asf_search/ASFSearchResults.md
      - ASFSession: asf_search/ASFSession.md
    - Exceptions: asf_search/exceptions.md
    - What's New: https://github.com/asfadmin/Discovery-asf_search/blob/master/CHANGELOG.md
  - ASF Search API:
    - Search API Basics: api/basics.md
    - Search API Keywords & Endpoints: api/keywords.md
    - Tools: api/tools.md
    - Troubleshooting: api/troubleshooting.md
    - Cookbook: api/cookbook.md
    - What's New: api/changelog.md
  # - About: about.md
  - Product Details:
    - Using ASF Data: datasets/using_ASF_data.md
    - ALOS PALSAR Products: datasets/palsar.md
    - Events (SARVIEWS): datasets/events_about.md
  - ASF Web: 'https://asf.alaska.edu/'
